### PR TITLE
add .gitignore files to border router

### PR DESCRIPTION
**Pull request by DuaneEllis-TI**
Various directories within the border router do not have .gitignore files
this PR adds them without causing problems with ignoring files in thirdparty

### CODE REVIEW

**Comment by DuaneEllis-TI** [comment]
@jwhui  or @bukepo  - can you look at this?

Hmm- I do not understand how adding .gitignore files causes this:

https://travis-ci.org/openthread/borderrouter/jobs/258732109#L4238

My hunch is - some security thing has changed on the travis build machines
that causes some security thing to trigger with dbus.

```
otbr-agent[7196]: NCP requesting DBus name otbr.agent.wpan0...
otbr-agent[7196]: NCP DBus error: Connection ":1.9" is not allowed to own the service "otbr.agent.wpan0" due to security policies in the configuration file!
otbr-agent[7196]: NCP failed to initialize!
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCP failed to initialize!
interfaceName not specified, using default wpan0
http port not specified, using default 80
otWeb[7197]: border router web started on wpan0
+netstat -an
+grep 49191
+die Service otbr-agent not ready!
+echo  *** ERROR:  Service otbr-agent not ready!
 *** ERROR:  Service otbr-agent not ready!
+exit 1
The command ".travis/script.sh" exited with 1.
cache.2
store build cache
0.00s
1.57schanges detected, packing new archive
uploading archive
Done. Your build exited with 1.
wpantund[7185]: [-NCP-]: Socket error on read: Broken pipe 32
wpantund[7185]: NCPInstance: errno 11 "Resource temporarily unavailable"
wpantund[7185]: Cleaning up. (gRet = 9)
```

**Comment by bukepo** [comment]
@DuaneEllis-TI Thanks for addressing this issue. Instead of provide a `.gitignore` in each sub-directory of top directory, is it possible to collect them into a single `.gitignore` in the top level directory for all first party files just like OpenThread? https://github.com/openthread/openthread/blob/master/.gitignore

**Comment by DuaneEllis-TI** [comment]
@bukepo  - Done
It seems the original problem (the error, with dbus on the Travis server) is intermittent, and/or not reproducible....  I don't know why...

Once this is done, I'll push up the other fix on the border router.

**Comment by DuaneEllis-TI** [comment]
@jwui - What is next?

**Pull request merged**
